[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_source = "tag"
version_variable = "swizzle/__init__.py:__version__"
upload_to_pypi = true
build_command = "python -m build"

[tool.pytest.ini_options]
testpaths = ["tests"]  

